/*
# Seed reference data and team roster from Malomatia workbook

## Source
Extracted from data/Malomatia_Form-Program.xlsm:
- Team Ref sheet -> agents (48 rows)
- REF sheet -> reference_options (rca/fcr/csat/aht/hold/sub_type categories)
- Glossary sheet -> glossary (30 definitions)

## Notes
- Uses ON CONFLICT DO NOTHING so re-running is safe.
- Strips header/sentinel rows (values ending with '_' were column-group markers).
*/

-- Agents (48 from Team Ref sheet)
INSERT INTO agents (agent_name, attendance_user, mena_me_code, team_leader, qa, lob) VALUES
  ('Rakan Abdelhadi', 'Rakan.Abdelhadi', '13397', 'Mohammad Murad', 'Yazan', 'Over Night'),
  ('Heba Othman', 'Hiba.Othman', '13069', 'Mohammad Murad', 'Yazan', 'Escalation'),
  ('Bayan Salah', 'Bayan.Salah', '13451', 'Mohammad Murad', 'Yazan', 'Escalation'),
  ('Hiba Hammoudeh', 'Hiba.Hammoudeh', '13579', 'Mohammad Murad', 'Yazan', 'Escalation'),
  ('Massa Ahmad', 'Massa.Alkhatib', '13064', 'Mohammad Murad', 'Yazan', 'Escalation'),
  ('Layan Saleh', 'Layan.Alnajjar', '12942', 'Mohammad Murad', 'Yazan', 'Escalation'),
  ('Aya Said', 'Ayah.Alghawi', '10604', 'Mohammad Murad', 'Yazan', 'Escalation'),
  ('Lama Mahmoud', 'Lama.Alshaikh', '13729', 'Mohammad Murad', 'Yazan', 'Escalation'),
  ('Anas Jawad', 'Anas.Abuhamidah', '14074', 'Mohammad Murad', 'Ghzaleh', 'Voice'),
  ('Abdalkader Bader', 'Abedalqader.Katbeh', '14263', 'Mohammad Murad', 'Yazan', 'Voice'),
  ('Malak Mohammad', 'Malak.Albanna', '13604', 'Mohammad Murad', 'Ghzaleh', 'Non-Voice'),
  ('Anas Hamdan', 'Anas.Hamdan', '14251', 'Mohammad Murad', 'Ghzaleh', 'Non-Voice'),
  ('Abdallah El Kouch', 'Abdallah.Elkouch', '14749', 'Mohammad Murad', 'Ghzaleh', 'Non-Voice'),
  ('Mahdi Alobally', 'Mahdi.Alobally', '14750', 'Mohammad Murad', 'Ghzaleh', 'Non-Voice'),
  ('Said AlSa''di', 'Said.Alsadi', '14751', 'Mohammad Murad', 'Yazan', 'Non-Voice'),
  ('Abdelrahman Hussein', 'Abdelrahman.Assaf', '13286', 'Rami Abuyounes', 'Yazan', 'Over Night'),
  ('Abdallah Ahmad', 'Abdallah.Altiti', '13449', 'Rami Abuyounes', 'Yazan', 'Over Night'),
  ('Basim Mohammad', 'Bassem.Mohammad', '14084', 'Rami Abuyounes', 'Ghzaleh', 'Over Night'),
  ('Rami Awni', 'Rami.Hamdan', '14077', 'Rami Abuyounes', 'Yazan', 'Over Night'),
  ('Shahd Khalil', 'Shahd.Abuserrieh', '14252', 'Rami Abuyounes', 'Yazan', 'Voice'),
  ('Mahmoud Hisham', 'Mahmoud.Qutaifan', '14259', 'Rami Abuyounes', 'Ghzaleh', 'Voice'),
  ('Liyan Nidal', 'Liyan.Khaireddin', '11484', 'Rami Abuyounes', 'Ghzaleh', 'Voice'),
  ('Dania Sameer', 'Danya.Bustamy', '14254', 'Rami Abuyounes', 'Yazan', 'Non-Voice'),
  ('Farah Ismael', 'Farah.Ismael', '13726', 'Rami Abuyounes', 'Ghzaleh', 'Non-Voice'),
  ('Fahed Khaled', 'Fahad.Sabha', '13735', 'Rami Abuyounes', 'Yazan', 'Non-Voice'),
  ('Hala Mohammed', 'Hala.Alnaimat', '14070', 'Rami Abuyounes', 'Ghzaleh', 'Non-Voice'),
  ('Maya Hashem', 'Maya.Helweh', '14261', 'Rami Abuyounes', 'Ghzaleh', 'Non-Voice'),
  ('Yasmeen Omar', 'Yasmeen.Hussein', '14265', 'Rami Abuyounes', 'Yazan', 'Non-Voice'),
  ('Farouq Shahrure', 'Farouq.Shahrure', '14746', 'Rami Abuyounes', 'Ghzaleh', 'Voice'),
  ('Esraa Sidair', 'esraa.sidair', '10728', 'Rami Abuyounes', 'Yazan', 'Non-Voice'),
  ('Ahed Hawas', 'Ahed.Abuhawas', '14745', 'Rami Abuyounes', 'Yazan', 'Non-Voice'),
  ('Rahaf Habboub', 'Rahaf.Habboub', '14747', 'Rami Abuyounes', 'Ghzaleh', 'Non-Voice'),
  ('Suliman Saleh', 'Suleiman.Saleh', '14081', 'Sobhi Akilah', 'Ghzaleh', 'Voice'),
  ('Rozan Mohsen', 'Rozan.Alhwaidi', '13450', 'Sobhi Akilah', 'Ghzaleh', 'Voice'),
  ('Marya Khaldoon', 'Marya.Yahya', '14267', 'Sobhi Akilah', 'Ghzaleh', 'Voice'),
  ('Hussam Hasan', 'Husam.Albaw', '14255', 'Sobhi Akilah', 'Yazan', 'Voice'),
  ('Sondos Nader', 'Sondos.Alakhras', '13246', 'Sobhi Akilah', 'Yazan', 'Voice'),
  ('Tawfiq Salah', 'Tawfiq.Assalah', '14258', 'Sobhi Akilah', 'Yazan', 'Non-Voice'),
  ('Zeina Zeyad', 'Zaineh.Habibeh', '14073', 'Sobhi Akilah', 'Yazan', 'Non-Voice'),
  ('Razan Ersan', 'Razan.Ersan', '13725', 'Sobhi Akilah', 'Ghzaleh', 'Non-Voice'),
  ('Adham Adnan', 'Adham.Alshorman', '14080', 'Sobhi Akilah', 'Ghzaleh', 'Non-Voice'),
  ('Salma Abdallah', 'Salma.Alshishani', '14253', 'Sobhi Akilah', 'Ghzaleh', 'Non-Voice'),
  ('Marah Marie', 'Marah.Kotban', '14262', 'Sobhi Akilah', 'Ghzaleh', 'Non-Voice'),
  ('Majd Al-Deen', 'Majd.abuobead', '14017', 'Sobhi Akilah', 'Ghzaleh', 'Voice'),
  ('Saif Abu Halawa', 'Saif.Abuhalawa', '14748', 'Sobhi Akilah', 'Yazan', 'Non-Voice'),
  ('Sumaia Yousef', 'sumaia.yousef', '14198', 'Sobhi Akilah', 'Ghzaleh', 'Non-Voice'),
  ('Waleed Yassin', 'Waleed.Sheikh', '14753', 'Sobhi Akilah', 'Ghzaleh', 'Non-Voice')
ON CONFLICT DO NOTHING;

-- Reference options (rca_l1, rca_l2, rca_l3, fcr_l1/l2/l3, csat, agent, aht, hold, sub_type, mistake_type, main_skill, monitoring_type, lob)
INSERT INTO reference_options (category, value, sort_order) VALUES
  ('rca_l1', 'Controlable_Factor', 0),
  ('rca_l1', 'Uncontrollable_Factor', 1),
  ('rca_l2', 'Knowledge', 0),
  ('rca_l2', 'Skill_Issue', 1),
  ('rca_l2', 'Communication', 2),
  ('rca_l2', 'Agent_Behavior', 3),
  ('rca_l2', 'CST_Behavior', 4),
  ('rca_l2', 'System_Issue', 5),
  ('rca_l2', 'Process_Limitation', 6),
  ('rca_l3', 'Quality of information: Incomplete', 0),
  ('rca_l3', 'Quality of information: Incorrect', 1),
  ('rca_l3', 'Quality of information: Unclear', 2),
  ('rca_l3', 'Agent did not take the proper action/Correct Troubleshooting', 3),
  ('rca_l3', 'Agent did not offer additional options/Alternatives', 4),
  ('rca_l3', 'New KB Update (Clarify in Comment)', 5),
  ('rca_l3', 'Rare Case (NHs Only)', 6),
  ('rca_l3', 'Agent asked CST relevant questions/paraphrasing confirming CST issue', 7),
  ('rca_l3', 'Agent Didn''t show Empathy', 8),
  ('rca_l3', 'Agent Wasn''t Reassuring the CST', 9),
  ('rca_l3', 'Agent did not use a positive tone', 10),
  ('rca_l3', 'Didn''t properly explain the background of the situation/Issue', 11),
  ('rca_l3', 'Poor Invisitagtion/didn''t Check  history & effectively used systems and tools', 12),
  ('rca_l3', 'High Incoming Concurency (Chat NHs Only)', 13),
  ('rca_l3', 'Lack of Concentration/Focus', 14),
  ('rca_l3', 'Active listening/Reading Understanding', 15),
  ('rca_l3', 'Invalid Silence gaps', 16),
  ('rca_l3', 'Invalid Hold time/Silence gap', 17),
  ('rca_l3', 'Follow-up Needed as per Process', 18),
  ('rca_l3', 'CSA Already Resigned', 19),
  ('rca_l3', 'Over-Promising on Purpose to Maintain High Scores', 20),
  ('rca_l3', 'Agent mistreating the customer [e.g., rudeness]', 21),
  ('rca_l3', 'Discipline/ Careless', 22),
  ('rca_l3', 'Credit Seeker/Fraudulent', 23),
  ('rca_l3', 'CST no Happy with Correct resolution provided (Clarify in Comment)', 24),
  ('rca_l3', 'Technical Issue with Headset (Clarify in Comment)', 25),
  ('rca_l3', 'Internet/System Outage (Clarify in Comment)', 26),
  ('rca_l3', 'Wording on KB Misleading (Clarify in Comment)', 27),
  ('rca_l3', 'Case Not Clear on KB (Clarify in Comment)', 28),
  ('rca_l3', 'Process impacts customer experience (Clarify in Comment)', 29),
  ('fcr_l1', 'Agent', 0),
  ('fcr_l1', 'Process', 1),
  ('fcr_l1', 'Customer', 2),
  ('fcr_l1', 'Technical', 3),
  ('fcr_l2', 'Agent', 0),
  ('fcr_l2', 'Process', 1),
  ('fcr_l2', 'Customer', 2),
  ('fcr_l2', 'Technical', 3),
  ('fcr_l3', 'Quality of information: Incomplete', 0),
  ('fcr_l3', 'Quality of information: Incorrect', 1),
  ('fcr_l3', 'Quality of information: Unclear', 2),
  ('fcr_l3', 'Agent did not take the proper action/Correct Troubleshooting', 3),
  ('fcr_l3', 'Agent did not offer additional options/Alternatives', 4),
  ('fcr_l3', 'Agent Didn''t show Empathy', 5),
  ('fcr_l3', 'Agent Wasn''t Reassuring the CST', 6),
  ('fcr_l3', 'Didn''t properly explain the background of the situation/Issue', 7),
  ('fcr_l3', 'Follow-up Needed as per Process', 8),
  ('fcr_l3', 'Over-Promising on Purpose to Maintain High Scores', 9),
  ('fcr_l3', 'Agent mistreating the customer [e.g., rudeness]', 10),
  ('fcr_l3', 'Discipline/ Careless', 11),
  ('fcr_l3', 'Credit Seeker/Fraudulent', 12),
  ('fcr_l3', 'CST no Happy with Correct resolution provided (Clarify in Comment)', 13),
  ('fcr_l3', 'Technical Issue with Headset (Clarify in Comment)', 14),
  ('fcr_l3', 'Internet/System Outage (Clarify in Comment)', 15),
  ('fcr_l3', 'Process impacts customer experience (Clarify in Comment)', 16),
  ('fcr_l3', 'Knowledge Gap (Clarify in Comment)', 17),
  ('csat', '1 (Critical)', 0),
  ('csat', '3 (Non Critical)', 1),
  ('csat', '5 (Normal)', 2),
  ('agent', 'Agent', 0),
  ('agent', 'Process', 1),
  ('agent', 'Customer', 2),
  ('agent', 'Technical', 3),
  ('aht', 'Exceed timeline on hold or mute', 0),
  ('aht', 'Documenting CST Complaint', 1),
  ('aht', 'Knowledge Gap (Clarify in Comment)', 2),
  ('aht', 'Agent not Aware of AHT (NH only)', 3),
  ('aht', 'System Outage (Clarify in Comment)', 4),
  ('aht', 'Long Time to Close', 5),
  ('aht', 'Double Chat (NH & Chat only)', 6),
  ('aht', 'Agent didn''t retain CST frustration/increased CST frustration', 7),
  ('aht', 'Lack of Focus', 8),
  ('aht', 'Control & Ownership of Call', 9),
  ('aht', 'Increased verification time from 2nd-line team', 10),
  ('aht', 'Normal', 11),
  ('hold', 'Knowledge Gap (Clarify in Comment)', 0),
  ('hold', 'Increased verification time from 2nd-line team', 1),
  ('hold', 'Needed further support', 2),
  ('hold', 'Evading CST complaint/issue', 3),
  ('hold', 'Not taking ownership of case/issue', 4),
  ('hold', 'Lack of Concentration (re-checking CST issue or solution provided)', 5),
  ('hold', 'Normal', 6),
  ('sub_type', 'Call Opening/ Closure', 0),
  ('sub_type', 'Choice of words / Avoid Slang / Technical Terms/ Customer name', 1),
  ('sub_type', 'Tone of voice', 2),
  ('sub_type', 'Showing Empathy / handling objection/Interrupting the Customer', 3),
  ('sub_type', 'Active listening', 4),
  ('sub_type', 'Hold', 5),
  ('sub_type', 'Customer Profile/ required data/', 6),
  ('sub_type', 'Correct information provided', 7),
  ('sub_type', 'Missing Information', 8),
  ('sub_type', 'Ticket Escalation and Status', 9),
  ('sub_type', 'Ticket description', 10),
  ('sub_type', 'Transfer Process', 11),
  ('sub_type', 'Professionalism/Attitude', 12),
  ('sub_type', 'Ticket creation and categorization for the closed Interactions', 13),
  ('sub_type', 'Control the call/ Comprehension /', 14),
  ('sub_type', 'Ticketing Tree', 15),
  ('mistake_type', '', 0),
  ('mistake_type', 'Non Critical', 1),
  ('mistake_type', 'End-user Critical', 2),
  ('mistake_type', 'Business Critical', 3),
  ('mistake_type', 'Compliance Critical', 4),
  ('main_skill', 'HMC', 0),
  ('monitoring_type', 'Program', 0),
  ('monitoring_type', 'Call Back', 1),
  ('monitoring_type', 'Live Call', 2),
  ('monitoring_type', 'Email', 3),
  ('monitoring_type', 'Chat', 4),
  ('lob', 'Voice', 0),
  ('lob', 'Non-Voice', 1),
  ('lob', 'Escalation', 2),
  ('lob', 'Over Night', 3)
ON CONFLICT DO NOTHING;

-- Glossary (30 definitions)
INSERT INTO glossary (section, attribute, description) VALUES
  ('Call Opening', 'Was the call opening was clear & within the onset time without distractions (5 seconds)', 'Agent should be ready to take the call.
Headset and mic should be always in place.
Agent should be seated in a quite area where he shouldn''t be distracted.
The call should be answered within 5 seconds.'),
  ('Call Opening', 'Personalized the Greeting ( Company name - Agent name)', 'The greeting should be mentioned in full mentioning the following details ( Thank you for calling(Brand Name), (Agent name)is speaking'),
  ('Call Opening', 'Assistance offered through using phrases (Example How May I Help you , How can I assist you)', 'Assistance should be offered during the greeting example: How can I help you, How may I assist you'),
  ('Verification', 'Verify customer phone number / member ID number/ order number whenever needed', 'Agent need to confirm the phone number or order number in order to verify customer profile, for Shukran email or DOB will be required to verify any change in customer account'),
  ('Telephone Etiquettes', 'Did the agent assure help', 'Assuring help after customer mentioning his/her concern by saying sure I will do my best to help you , of course I will try to check all possible reasons to help you'),
  ('Telephone Etiquettes', 'Asking relevant or logical questions to identify customer concern (probing)/paraphrasing', 'Probing should be done using open ended questions like could you tell me more about your order or what happened exactly /Agent need to paraphrase customer inquiry to ensure that we are aligned with the customer request'),
  ('Telephone Etiquettes', 'the tone voice was matching the customer enthusiasm and or excitement ( Voice Impact)', 'Agent tone of voice should be smiley and match the customer tone of voice, sleepy/negative/ monotonous tone of voice will'),
  ('Telephone Etiquettes', 'build a good rapport with the customer using empathy or good response', 'Building rapport must be done by using smiley tone of voice
showing empathy/ good response should be done immediately by apologizing to the customer when needed or reflect his emotions'),
  ('Telephone Etiquettes', 'addressed the customer by using his/her name with the appropriate title (Except KSA)', 'Using customer name during the call at least 3 times depend on the call duration(beginning of the call , middle of the call& end of the call)'),
  ('Telephone Etiquettes', 'speak with the customer in proper language/ style/negative words', 'Agent should use same language that customer using and to avoid ordering language or negative words'),
  ('Telephone Etiquettes', 'Call Duration was aligned with the customer request', 'Call duration should be matching the call scenario not too long and not too short'),
  ('Telephone Etiquettes', 'Did the agent focused on the customer request without missing or requesting repeating his query', 'Focus with the customer inquiries without missing any of it or requesting the customer to repeat it ( Lack of focus)'),
  ('Telephone Etiquettes', 'Agent did not interrupt / speak over the customer "Clipping"', 'Agent should wait for the customer to complete his sentence without interruption or asking the customer to stop talking in order for him to speak'),
  ('Telephone Etiquettes', 'Did the agent showed confidence or expertise in providing information to the customer', 'agent should be easy to be understood by using structured and organized manner to explain things to customer'),
  ('Telephone Etiquettes', 'Did the agent use slangs/jargons', 'Using any slang word like ( Ok, yea, Nop, Wanna , Gonna) or Jargons like internal words  ( WWD,FD, etc.) is not allowed'),
  ('Hold & transfer protocol', 'informed the customer with the held activities during the call ( Dead air)', 'Dead Air should not exceed 30 sec max per pause and will be scored based on the call duration , agent should engage the customer with the activities to avoid the dead air'),
  ('Hold & transfer protocol', 'Did the agent follow the correct hold protocol', 'the Hold script should be used for placing the call on hold and it should not exceed 2 mins per hold ( May I place the call on hold for 2 mins in order to check more information for you )'),
  ('Hold & transfer protocol', 'Did the agent follow the correct call transfer protocol', 'in case required , call should be transferred warmly where the agent need to inform the BO agent or team leader about the customer problem then need to provide the customer with name of the person who will take over the call'),
  ('Hold & transfer protocol', 'Using Mute instead of Hold', 'Mute is not allowed during the call for any reason, in case the agent need any assistance , they can use the hold'),
  ('Call Closing', 'Did the agent offer the customer further assistance', 'Agent should offer any further assistance to the customer even if the customer asked for any inquiry , customer should be offered further assistance again'),
  ('Call Closing', 'Did the Agent promote the C-Sat survey', 'C-sat is mandatory to be mentioned by end of each call unless the customer has not been served due to system issue'),
  ('Call Closing', 'Did the Agent promote self service/ app download', 'Agent to promote the app or guide the customer of any self service that he can do using the mobile app / offer the customer to download the app for better experience'),
  ('Call Closing', 'Did the Agent recap and close the call properly', 'Call closure should be branded and to include a recap for the case resolution'),
  ('Process', 'Did the agent gather the right information needed to check customer request', 'Agent should check the customer history and if the same case escalated before also collect from the customer any related information in case he called before'),
  ('Process', 'Did the agent checked any related tickets/notes/child ticket for customer issue in case any', 'Any feedback that has been provided on any previous tickets agent should use it and inform the customer about it , also in case any reply that should be gathered from the customer to update the ticket it should be done as well'),
  ('Process', 'Did the agent offered/ Suggested all reasonable alternatives to fulfil customer''s needs', 'Agent need to provide the customer with all the possible resolutions if any as well as guiding or educating the customer about the next steps'),
  ('Process', 'Did the agent take ownership by set caller expectation on time frame, process , etc.', 'agents to provide the customer with the time frame /Process resolution time'),
  ('Documentation', 'Did the agent dispose the call correctly', 'ticket disposition must be correct with full notes'),
  ('Documentation', 'Ticket remarks need to be added clearly by agent in case of new ticket or private note.', 'Ticket remarks should represent the issue of the customer with the clear action that needs to be taken'),
  ('Documentation', 'Did the agent create a new ticket rather than updating the existing ticket.', 'Agent must avoid creating a new ticket since another old ticket is opened, and he needs to add a private note about the customer follow up'),
  ('Auto Fail', 'Did the Agent mislead the customer or used deceptive conduct', 'Agent should provide the customer with all the correct information related to his query ( refund timeline, return processed.) failing to provide all related information will be considered as misleading the customer'),
  ('Auto Fail', 'Did the agent create the right ticket on FD/Did the agent follow the correct escalation process', 'Correct escalation needs to be done, as per the scenario to the relevant team with all the correct details.
In case if issue needs to be raised agent should raise it to the concerned team'),
  ('Auto Fail', 'Has the agent behavior was falling under Misrepresentation ( Yelling, screaming, rudeness & sarcasm)', 'Any misbehavior showed by the agent( rudeness, Screaming , yelling or sarcasm ) is not allowed and will be falling under Zero tolerance policy'),
  ('Auto Fail', 'Call Avoidance ( Delayed call opening , disconnecting the calls )', 'any delay on call opening will be consider as avoiding calls as well as disconnecting the call/using system issue verbiage without a confirmation by TL will be considered as call avoidance')
ON CONFLICT DO NOTHING;